// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appglobal;

namespace materi_docker.models.migrations
{
    [DbContext(typeof(webapi_db))]
    partial class webapi_dbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("appglobal.m_bulan", b =>
                {
                    b.Property<int>("m_bulan_id");

                    b.Property<string>("m_bulan_nama")
                        .HasMaxLength(10);

                    b.HasKey("m_bulan_id");

                    b.ToTable("m_bulan");
                });
#pragma warning restore 612, 618
        }
    }
}
