version: "3"
services:
  sql:
    container_name: mariadb_c
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: mypassword
    networks: 
      db:
        aliases:
          - sql
    restart: always
    
  webapi:
    container_name: webapi_run
    image: webapi
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "51234:80"
    restart: on-failure
    networks: 
      - web
      - db

networks:
  web:
  db: