version: "3"
services:
  webapi:
    container_name: webapi_run
    image: webapi
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "51234:80"
    networks: 
      - web
      - db
      
  mariadb_docker:
    container_name: mariadb_docker
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: mypassword
    networks: 
      db:
        aliases:
          - sql
networks:
  web:
  db: