version: "3"
services:
  mariadb_docker:
    container_name: mariadb_docker
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: mypassword
    ports: 
      - "50001:3306"
    
  webapi:
    container_name: webapi_run
    image: webapi
    build: 
      context: . 
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "51234:80"
    links: 
      - mariadb_docker