version: "3"
services:
  mariadb_docker:
    container_name: mariadb_docker
    image: 172.16.200.127:5000/mariadb-pds
    environment: 
      MYSQL_ROOT_PASSWORD: mypassword
    ports: 
      - "50001:3306"
    
  webapi:
    container_name: webapi_run
    image: 172.16.200.127:5000/dotnet-initbuild-2
    restart: always
    ports: 
      - "51234:80"
    links: 
      - mariadb_docker